# Generated by Django 2.2 on 2020-06-16 17:13

from django.db import migrations, models
import django.db.models.deletion
import team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('team_id', models.CharField(default=team.models.create_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('member_name', models.CharField(default=team.models.create_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammember', to='team.team')),
            ],
        ),
    ]
